# generated by datamodel-codegen:
#   filename:  NIST_V2_election_results_reporting.json
#   timestamp: 2021-09-09T23:34:22+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import ElectionResults


class Model(BaseModel):
    __root__: ElectionResults.ElectionReport
